name: Update gist
on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
    
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Update gist
        uses: maxam2017/productive-box@v1.1.1
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 316c43d64113ce2f0879f26acc5ec9e7
          TIMEZONE: Europe/Paris
